# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'projects.html'}
- {name: 'News', path: 'menu', url: 'news.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/efriel94'}
- {icon: 'twitter', link: 'https://twitter.com/friel_emmet'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/efrielcsit2894/'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  paginate: 3
  paginate_path: "/blog/page:num/" 
  next_page: 'Next'
  previous_page: 'Back'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
